CREATE TABLE shortened_url (
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   short_url VARCHAR(2048) NOT NULL,
   origin_url VARCHAR(2048) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);